
name: Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Extract Maven project version
      run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
      id: pom-version

    - name: Bild tag version
      run: echo ::set-output name=version::$(echo ${{ steps.pom-version.outputs.version }}-${{github.run_number}}-${GITHUB_SHA::7})
      id: tag-version
    
    - name: Maven build
      run: mvn clean install
            
    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ github.actor }}
        password: ${{secrets.dockerhub_token}}   
        
    - name: Build and Push Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: aunghtayoo/spring-rest-helloworld:${{ steps.tag-version.outputs.version }}
